const subscribers = [
    {
        registrationDate: "02.06.2022",
        registrationTime: "22:20:00",
        userID: "78523972",
        firstName: "Карина",
        lasrName: "Трофимова",
        username: "@nekashtanka",
        box: "box",
        company: "google",
        phoneNumber: "+7293752393952",
        name: "ЛОХ",
        email: "trodiso@ivs.ru",
        telephony: "СВОЯ телефония",
        robotType: "robotType",
        numberOfPhones: "количество", 
        CRMName: "crm",
        CMS: "Карина - лох",

    },
    {
        registrationDate: "22.06.2022",
        registrationTime: "00:20:00",
        userID: "46930862",
        firstName: "Николай",
        lasrName: "Николаев",
        username: "@лох",
        box: "box",
        company: "google",
        phoneNumber: "+7293752393952",
        name: "ЛОХ",
        email: "trodiso@ivs.ru",
        telephony: "СВОЯ телефония",
        robotType: "robotType",
        numberOfPhones: "количество", 
        CRMName: "crm",
        CMS: "Карина - лох",

    }
]